import type { Metadata } from 'next'

import { Geist_Mono, Montserrat } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

const montserrat = Montserrat({
  subsets: ['latin', 'latin-ext'],
  variable: '--font-sans',
})

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={cn('h-full', 'antialiased', montserrat.variable, geistMono.variable, 'font-sans')} lang='en'>
      <body className='flex min-h-full flex-col'>{children}</body>
    </html>
  )
}
