import type { CollectionConfig } from 'payload'
import type { TLabel } from '@/translations'

import { hookSetCatalogPrefix } from './media-catalog-prefix-hook'
import { hookDeriveMediaMetadata } from './media-derive-metadata-hook'
import { hookDeleteCatalogPages, hookGenerateCatalogPages } from './media-generate-pages-hook'
import { hookEnsureUniqueTitleInCatalog } from './media-unique-title-hook'

export const Media: CollectionConfig = {
  access: {
    read: () => true,
  },

  admin: {
    defaultColumns: ['title', 'catalog', 'letter', 'filename', 'updatedAt'],
    // Group By → Catalog gives a "folders per catalog" view without a separate folder taxonomy
    groupBy: true,
    useAsTitle: 'title',
  },

  fields: [
    {
      admin: {
        components: {
          Field: '/collections/media/duplicate-media-guard#DuplicateMediaGuard',
        },
        disableListColumn: true,
      },
      name: 'duplicateGuard',
      type: 'ui',
    },
    {
      // Auto-derived from the PDF filename when left empty
      admin: {
        description: ({ t }: TLabel) => t('custom:media:fields:title:description'),
      },
      label: ({ t }: TLabel) => t('custom:media:fields:title:label'),
      name: 'title',
      required: true,
      type: 'text',
    },
    {
      // Multi-tenant plugin automatically filters options to current tenant's catalogs
      index: true,
      label: ({ t }: TLabel) => t('custom:media:fields:catalog'),
      name: 'catalog',
      relationTo: 'catalogs',
      required: true,
      type: 'relationship',
    },
    {
      admin: {
        description: ({ t }: TLabel) => t('custom:media:fields:letter:description'),
        readOnly: true,
      },
      index: true,
      label: ({ t }: TLabel) => t('custom:media:fields:letter:label'),
      name: 'letter',
      type: 'text',
    },
    {
      admin: {
        description: ({ t }: TLabel) => t('custom:media:fields:slug:description'),
        disableListColumn: true,
      },
      index: true,
      label: ({ t }: TLabel) => t('custom:media:fields:slug:label'),
      name: 'slug',
      type: 'text',
    },
    {
      admin: {
        description: ({ t }: TLabel) => t('custom:media:fields:categories:description'),
      },
      label: ({ t }: TLabel) => t('custom:media:fields:categories:label'),
      name: 'categories',
      type: 'text',
    },

    // Overrides of fields generated by upload/plugin storage — Payload merges them with base fields by name, so we only hide the column option in the list view
    {
      admin: {
        disableListColumn: true,
      },
      name: 'mimeType',
      type: 'text',
    },
    {
      admin: {
        disableListColumn: true,
      },
      name: 'filesize',
      type: 'number',
    },
    {
      admin: {
        disableListColumn: true,
      },
      name: 'width',
      type: 'number',
    },
    {
      admin: {
        disableListColumn: true,
      },
      name: 'height',
      type: 'number',
    },
    {
      admin: {
        disableListColumn: true,
      },
      name: 'thumbnailURL',
      type: 'text',
    },
    {
      admin: {
        disableListColumn: true,
      },
      name: 'url',
      type: 'text',
    },
    {
      admin: {
        disableListColumn: true,
      },
      name: 'prefix',
      type: 'text',
    },
    {
      admin: { disableBulkEdit: true, disableListColumn: true, hidden: true },
      index: true,
      name: 'createdAt',
      type: 'date',
    },
  ],

  hooks: {
    afterChange: [hookGenerateCatalogPages],
    beforeDelete: [hookDeleteCatalogPages],
    beforeOperation: [hookSetCatalogPrefix],
    // Order matters: anti-duplicate relies on computed data.title
    beforeValidate: [hookDeriveMediaMetadata, hookEnsureUniqueTitleInCatalog],
  },

  // Hard guarantee at the database level — hook is not atomic with concurrent writes
  indexes: [
    {
      fields: ['title', 'catalog'],
      unique: true,
    },
  ],

  labels: {
    plural: ({ t }: TLabel) => t('custom:media:plural'),
    singular: ({ t }: TLabel) => t('custom:media:singular'),
  },

  slug: 'media',

  upload: {
    // PDFs don't have generated thumbnails — without this, the filename column
    // renders an empty placeholder image next to the file name
    displayPreview: false,
    mimeTypes: ['application/pdf'],
  },
}
